# -*- coding: utf-8 -*-
"""ItemCountRuntime.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i5zFqxRe5SetA8BekBIj3R8qgBovBWff
"""

import time
item_counts = [2, 3, 4, 5, 6, 7, 8, 10, 12, 15]
runtime_items = []

num_transactions = 500000

for n in item_counts:
    data = []
    for _ in range(num_transactions):
        txn = {}
        for i in range(n):
            item = chr(ord('A') + i)
            txn[item] = round(random.uniform(0.0, 1.0), 2)
        data.append(txn)

    start = time.time()
    top_k = top_k_bayesian_networks(data, min_support=0.3, K=5, weight_support=0, sample_size=3000)
    end = time.time()

    runtime_items.append(end - start)

# Plot
plt.figure(figsize=(11, 5))
plt.plot(item_counts, runtime_items, 'o-', color='red')
plt.xlabel("Number of Items")
plt.ylabel("Runtime (seconds)")
plt.title("Runtime vs. Number of Items")
plt.grid(True)
plt.tight_layout()
plt.show()