# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i5zFqxRe5SetA8BekBIj3R8qgBovBWff
"""

from algorithm import top_k_bayesian_networks
import csv
import random

def load_csv(filename):
    data = []
    with open(filename, newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            data.append({k: float(v) for k, v in row.items()})
    return data

def generate_random_data(n_transactions, n_items):
    data = []
    for _ in range(n_transactions):
        txn = {}
        for i in range(n_items):
            item = chr(ord('A') + i)
            txn[item] = round(random.uniform(0.0, 1.0), 2)
        data.append(txn)
    return data

def get_static_data():
    return [
        {"A": 0.1, "B": 0.1},
        {"A": 0.9, "C": 0.8},
        {"B": 0.3, "D": 0.4},
        {"C": 0.9, "D": 0.95},
        {"B": 0.2, "C": 0.1},
    ]

if __name__ == "__main__":
    print("=== Top-K Bayesian Network Search ===")
    mode = input("Select data mode (static / csv / random): ").strip().lower()

    if mode == "csv":
        path = input("Enter CSV file path: ").strip()
        data = load_csv(path)
    elif mode == "random":
        n_txn = int(input("Number of transactions: "))
        n_items = int(input("Number of items: "))
        data = generate_random_data(n_txn, n_items)
    else:
        data = get_static_data()

    # Get algorithm parameters
    min_support = float(input("Enter min support (e.g. 0.3): "))
    K = int(input("Enter top-K (e.g. 5): "))
    weight_support = float(input("Enter weight for support in scoring (e.g. 0): "))
    sample_size = int(input("Enter sample size (0 = full data): "))
    if sample_size == 0 or sample_size > len(data):
        sample_size = None

    print("\nRunning Top-K search...")
    topK = top_k_bayesian_networks(data, min_support, K, weight_support, sample_size)

    for idx, (edges, score) in enumerate(topK, 1):
        print(f"Top-{idx}: Edges = {sorted(edges)}, Score = {score:.4f}")