# -*- coding: utf-8 -*-
"""NetworkComplexity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i5zFqxRe5SetA8BekBIj3R8qgBovBWff
"""



import matplotlib.pyplot as plt
scores = []
edge_counts = []
for edges, score in topK:
    scores.append(score)
    edge_counts.append(len(edges))
plt.figure(figsize=(8, 5))
plt.plot(edge_counts, scores, 'o-', color='blue')
plt.xlabel('Number of Edges in DAG')
plt.ylabel('Score (BIC + Support)')
plt.title('Top-K Bayesian Networks: Score vs. Network Complexity')
plt.grid(True)
plt.tight_layout()
plt.show()