# -*- coding: utf-8 -*-
"""runtime.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i5zFqxRe5SetA8BekBIj3R8qgBovBWff
"""



import time
import random
import matplotlib.pyplot as plt

n_trials = [100, 1000, 10000, 100000, 200000, 300000, 500000]  # number of transactions
times = []

for t in n_trials:
    data = []
    for _ in range(t):
        data.append({
            "A": round(random.uniform(0, 1), 2),
            "B": round(random.uniform(0, 1), 2),
            "C": round(random.uniform(0, 1), 2),
            "D": round(random.uniform(0, 1), 2),
            "A1": round(random.uniform(0, 1), 2),
            "B2": round(random.uniform(0, 1), 2),
            "C3": round(random.uniform(0, 1), 2),
            "D4": round(random.uniform(0, 1), 2),
        })
    start = time.time()
    topK = top_k_bayesian_networks(data, min_support, K, weight_support, sample_size=3000)
    end = time.time()

    times.append(end - start)

# Plot
plt.plot(n_trials, times, 'o-', color='green')
plt.xlabel("Number of Transactions")
plt.ylabel("Runtime (seconds)")
plt.title("Runtime vs. Number of Transactions")
plt.grid(True)
plt.show()